name: corke
description: A retro digital scrapbook application
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  google_sign_in: ^6.1.5
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  provider: ^6.1.1
  uuid: ^4.2.1
  image: ^4.1.3
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
  fonts:
    - family: Kalam
      fonts:
        - asset: fonts/Kalam-Regular.ttf
        - asset: fonts/Kalam-Bold.ttf
          weight: 700